--- 
abstract: process handling and message passing, Erlang style
author: Anton Berezin  C<< <tobez@tobez.org> >>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: bsd
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: IPC-Messaging
no_index: 
  directory: 
    - devel
    - inc
    - t
requires: 
  B::Generate: 0
  IO::Select: 0
  IO::Socket::INET: 0
  IO::Socket::UNIX: 0
  Storable: 0
  Time::HiRes: 0
  perl: 5.6.0
version: 0.01_05
