---
abstract: 'process handling and message passing, Erlang style'
author:
  - 'Anton Berezin  C<< <tobez@tobez.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IPC-Messaging
no_index:
  directory:
    - devel
    - inc
    - t
recommends:
  IO::Epoll: 0
  IO::KQueue: 0
requires:
  B::Generate: 0
  IO::Select: 0
  IO::Socket::INET: 0
  IO::Socket::UNIX: 0
  Module::Load::Conditional: 0
  Storable: 0
  Time::HiRes: 0
  perl: 5.8.0
resources:
  license: http://opensource.org/licenses/bsd-license.php
version: 0.01_13
