#! /usr/bin/perl
use strict;
use warnings;
use lib qw(lib ../lib);
use IPC::Messaging;

my $prog = IPC::Messaging->popen("tail -F /var/log/maillog");
receive_loop {
	got stdout => $prog => then {
		my ($m, $d) = @_;
		print $d->{line} if $d->{line} =~ /removed/;
	};
};
